### ISSUE TITLE
Serialize the parser?

### ISSUE THREAD

**Issue by pixelrebel** [HearthSim/python-hearthstone#13]
I'm trying to save a parser object in a redis key/value store.    I am able to pickle the parser on complete logs (i.e. `parser.read()`), but when pickling a parser mid stream  (i.e. `parser.read_line()`)
I get pickling errors.

This example runs successfully for a while until a bit after a new game is started then fails on the `pickle.dumps` line.

```
pickled = None

def test(line):
  global pickled
  if pickled:
    parser = pickle.loads(pickled)
  else:
    parser = LogParser()
  parser.read_line(line)
  pickled = pickle.dumps(parser)
```

`AttributeError: Can't get attribute 'Player' on <module 'hearthstone.hslog.packets' from '/lib/python3.4/site-packages/hearthstone/hslog/packets.py'>`
`Can't pickle <class 'hearthstone.hslog.packets.CreateGame.Player'>: it's not found as hearthstone.hslog.packets.Player`

Is there a way to export/import game data so I can pick up where I left off?

**Comment by jleclanche** [comment]
You can use [python-hsreplay](https://github.com/hearthsim/hsreplay/) to export a packet tree to XML. It's the same XMLs that Joust reads into replays: https://hsreplay.net/replay/vZEz7JoNnfgVo34HJUHhEF

Does that do it? What are you trying to do exactly?

**Comment by pixelrebel** [comment]
Thanks for the quick reply @jleclanche.  

I'm tracking logs streaming in from logstash/rabbitmq.  If my tracker crashes/restarts, I want my parsers to persist and pickup mid-game when the tracker starts again.  Currently, my tracker stores the parsers in memory, so if it restarts, it can't initialize the current game ("No game available") even though no log lines were dropped.

**Comment by jleclanche** [comment]
Wouldn't it make more sense to just restart parsing from the beginning of the game? This seems like an edge case that isn't really worth the extra hassle.

**Comment by pixelrebel** [comment]
Yes, this would require a different approach.   Instead of reading the logs from a rabbitmq stream, I should probably send the logs to a DB like elasticsearch then just query the last 30mins every 500 ms.  I was avoiding this approach because it adds latency, and I'm trying to track many games in realtime.  But, like you say, it's an edge case that is unlikely (as long as I write a durable program). ;)

Thanks for spending the time to talk it out with me.

**Comment by jleclanche** [comment]
No problem! You should swing by our developer channel, by the way: https://hearthsim.info/join/

I'd love to hear more about what you're working on.
