### ISSUE TITLE
How does quest tracking work?

### ISSUE THREAD

**Issue by pixelrebel** [HearthSim/python-hearthstone#16]
My little script parses each line as it is written to the log.  I seem to be unable to access the quest tags.  I've tried something like the following

```
...
game = packet_tree.export().game
print game.tags.get(GameTag.QUEST)
print game.tags.get(GameTag.QUEST_PROGRESS)
print game.tags.get(GameTag.QUEST_PROGRESS_TOTAL)
for player in game.players:
  print player.tags.get(GameTag.QUEST)
  print player.tags.get(GameTag.QUEST_PROGRESS)
  print player.tags.get(GameTag.QUEST_PROGRESS_TOTAL)

```

Which returns 
```
None
None
None
None
None
None
```
What am I doing wrong?

**Comment by jleclanche** [comment]
The default `export()` will export the *final* game state (see [here](https://github.com/HearthSim/python-hslog/blob/master/README.md)). If you want to track progress over time, you have to iterate over the blocks yourself. I recommend writing a custom exporter, which looks at tag changes for those specific tags.
