### ISSUE TITLE
Blizzard Deckstrings didn't work for me 

### ISSUE THREAD

**Issue by zyi1992** [HearthSim/python-hearthstone#17]
I want to get the deckstrings use you program in python hearthston 
i use the data as below and i get the id from hearthstonejson 
heroes 813
format 2
cards [(279, 2), (42046, 1), (613, 2), (40938, 2), (1099, 2), (41935, 1), (41169, 2), (39442, 2), (1363, 2), (40373, 2), (1014, 2), (1367, 2), (41176, 2), (41177, 2), (39034, 2), (30, 2)]
when i run the program i got a code like this 
ACgxLCkoMiwpKDEsKSgxNzMsKSg2LCkoMiwpKDE5MCwpKDIwMCwpKDIsKSgyMDcsKSgxOTksKSgyLCkoMTQsKSgxNTEsKSgyLCkoMjI5LCkoNCwpKDIzNCwpKDE5MSwpKDIsKSgyMDMsKSg4LCkoMjA5LCkoMTkzLCkoMiwpKDE0NiwpKDE4MCwpKDIsKSgyMTEsKSgxMCwpKDE4MSwpKDE4NywpKDIsKSgyNDYsKSg3LCkoMjE1LCkoMTAsKSgyMTYsKSgxOTMsKSgyLCkoMjE3LCkoMTkzLCkoMiwpKDI1MCwpKDE3NiwpKDIsKSgzMCwpKDAsKQ==
this obviously not the right code  ,Is there anything wrong for my data, Glad for you replay

**Comment by azeier** [comment]
Could you post your code that produces that string?

**Comment by zyi1992** [comment]
I have got the reason, your code run in python3 but i test in python 2.7 , There  are a problem when use 'bytes' in python 2.7 , i change it to 'bytearray' and everything seem to be ok, thanks anyway

**Comment by jleclanche** [comment]
Yes, the deckstrings module is only python3-compatible.
