### ISSUE TITLE
Parser Is Reporting Uncollectible Cards In Player Decklists

### ISSUE THREAD

**Issue by amw2104** [HearthSim/python-hearthstone#19]
For Fatespinner the parser is reporting the uncollectible token: ICC_047t (DBF: 43430) instead of ICC_047 (42615). Example Replays:

https://hsreplay.net/replay/pCTRqUXTMuir6gcH9f7Hg2
https://hsreplay.net/replay/ZqraBPC9XXV8ccCucuR2ZT
https://hsreplay.net/replay/75FaNkvuA2zZwCdS4rbETW
https://hsreplay.net/replay/vcJrnPATyyvL2PZ3BEXFLV
https://hsreplay.net/replay/tvetYky3m3aH4LtURoGqwf
https://hsreplay.net/replay/mMGSM7V9uNLNMDX5oF8gn4
https://hsreplay.net/replay/BhGCZPmGTGbcmoD26kFsQM
https://hsreplay.net/replay/7LQaQMLNkCAgTvk9dQeRiB
https://hsreplay.net/replay/86PcHStXTsEtQykvk93GRN
https://hsreplay.net/replay/RPjkFYVhkt3BcS5mvNvijJ

**Comment by jleclanche** [comment]
@beheh didnt we fix this?

**Comment by beheh** [comment]
This is fixed with c95cce109f3e833405c2d194670292ff05133de1.
