### ISSUE TITLE
Attribute error in Zone class raised from fireplace test

### ISSUE THREAD

**Issue by d3sm0** [HearthSim/python-hearthstone#22]
tests_hero_powers from fireplace library seems raising an attribute error due to the missing attribute in Zone.DISCARD, which appear to be missing in this line. Can this simply be fixed with?
`DISCARD = 8`

https://github.com/HearthSim/python-hearthstone/blob/35e104920747da00fdb72e22802c0e8aee30407b/hearthstone/enums.py#L766

**Comment by jleclanche** [comment]
This is something that needs to be fixed in fireplace. There is no discard zone in HS, that was something I had implemented at the time for simplicity (splitting the graveyard and discards). Hop on the [discord server](https://discord.gg/hearthsim-devs) if you wanna chat about that.
