### ISSUE TITLE
Windows Python 3.6 Datetime Bug

### ISSUE THREAD

**Issue by Spedwards** [HearthSim/python-hearthstone#24]
A bug was introduced in the Windows version of Python 3.6 which causes `datetime.fromtimestamp(0)` [to throw an error](https://bugs.python.org/issue29097).

https://github.com/HearthSim/python-hearthstone/blob/480aa966aaf81b09615d4d0f86978de1f537703e/hearthstone/utils.py#L59

A quick fix for this is to replace the line above with `datetime(1, 1, 1)`.

**Comment by jleclanche** [comment]
This is https://bugs.python.org/issue29097 which has a fix in https://github.com/python/cpython/pull/2385 ...

I'm just not going to bother fixing that out of principle maybe. We don't support windows, so I'm fine not fixing it until 3.7.

**Comment by jleclanche** [comment]
I ended up fixing this anyway because the fix didn't land in Python 3.7 :(

**Comment by sebastientromp** [comment]
Thanks Jérôme, you've just saved me a few failed runs :)

**Comment by jleclanche** [comment]
Question is why are you still using Windows? :p
