### ISSUE TITLE
Module error

### ISSUE THREAD

**Issue by psydinger** [HearthSim/python-hearthstone#26]
Hi guys!

Just installed python-hearthstone (v 4.3.6) via pip on Windows 10:
In my code, if I `import hearthstone` and try to access `hearthstone.deckstrings.parse_deckstring()`, I get `module hearthstone has no deckstrings attribute`. 

On the other hand,  `from hearthstone import deckstrings` does let me access `deckstrings.parse_deckstring()` correctly. Im using Python version 3.6.5

Why is that? Is it an issue of the module, or am I doing something wrong?

Would be really glad if you could help me out! Thanks in advance! :)

**Comment by jleclanche** [comment]
This is due to the way Python modules and module name access works. The short answer is "it makes sense even though it's unintuitive".

`from hearthstone import deckstrings` is the correct usage.
