### ISSUE TITLE
Hidden CHANGE_ENTITY results in invalid initial_card_id

### ISSUE THREAD

**Issue by beheh** [HearthSim/python-hearthstone#27]
Hidden CHANGE_ENTITY's result in non-collectible cards being in the initial deck. More specifically, `entities = player.initial_deck` will have entities where `entity.initial_card_id` is a card that was changed in the opponents hand. For some cards, such as transformed Worgens/identitied items/upgraded Spellstones we can reasonably assume that the cards were their non-transformed/unidentified/base Spellstone at the beginning of the game.

In hsredshift, we use a [manually maintained map](https://github.com/HearthSim/hsredshift/blob/eeeed17decceefc7160ead5dbfdf1c5eebab788a/hsredshift/etl/records.py#L173-L229) to correct these deck lists. We should make sure we also apply this for all games processed on HSReplay.net. For the sake of having a single source of truth, we could implement this map in HSReplay.net.

If we think this doesn't make sense in the library, we should reopen an issue on HSReplay.net and implement the map there as well. In that case we'd need to maintain two lists though (one in hsredshift and one in HSReplay.net), as the Redshift exporter directly uses the `python-hearthstone` exporter and does not pass through the HSReplay.net codebase.

**Comment by joolean** [comment]
@beheh What is the incorrect behavior we're currently seeing in HSReplay.net? (Or elsewhere?)

**Comment by beheh** [comment]
Deck lists tracked for partial opposing decks in RDS are incorrect. We are planning to get rid of those eventually, but the proposal here is to move that behaviour into this library and maintain it here, instead of keeping this inside hsredshift.
