### ISSUE TITLE
STANDARD_SETS does not include HOF

### ISSUE THREAD

**Issue by tonyyyye** [HearthSim/python-hearthstone#28]
STANDARD_SETS has dynamic card sets as YEAR and HOF(Hall of Fame) changes.
However the card set definition of some cards cannot match the newest ones.

This comes with the problems when set to the past years such as ZodiacYear.KRAKEN or set to the WILD env.

**Comment by jleclanche** [comment]
HOF is not Standard. When a card is in HOF, it is Wild.
