### ISSUE TITLE
Player.initial_deck is sometimes missing cards

### ISSUE THREAD

**Issue by beheh** [HearthSim/python-hearthstone#6]
Downstream issue: HearthSim/HSReplay.net#43

[This log file](https://gist.github.com/beheh/6cf25812863e4a62e2f22bce4ac3699b) is missing cards in the initial_deck of player "Red1010". The replay itself contains a lot more cards (a seen in the [replay](https://hsreplay.net/replay/Su25oGmQg79RFXLFuj8qMC)).

I'm testing with the following script:

```python
import sys
from datetime import datetime
from hsreplay.dumper import parse_log

file = open(sys.argv[1], "r")
parser = parse_log(file, processor="GameState", date=datetime.now())
file.close()
game_tree = parser.games[0]

for player in game_tree.game.players:
    print("Found player %s" % player.name)
    for card in player.initial_deck:
        print("...with card %s" % card)
```

...and am only getting the following cards for the second player:

```
Found player Red1010
...with card Card(id=60, card_id='EX1_391')
...with card Card(id=61, card_id=None)
...with card Card(id=62, card_id=None)
...with card Card(id=63, card_id=None)
...with card Card(id=64, card_id=None)
...with card Card(id=65, card_id=None)
...with card Card(id=66, card_id=None)
...with card Card(id=67, card_id='OG_283')
```

**Comment by beheh** [comment]
It seems to be boiling down to this, hardcoded check: https://github.com/HearthSim/python-hearthstone/blob/6d233b5fabe8b8ebf0f966917b2b657e234e6413/hearthstone/entities.py#L99

Seems pretty flakey to me - especially in brawls or adventures, where deck sizes may vary (and where no deck list is supplemented from the uploading client).

**Comment by jleclanche** [comment]
I don't think there's really a surefire way of getting the deck. And now that I remember, setaside cards will break the algorithm too.

**Comment by beheh** [comment]
I'm sure we can think of a way - maybe by looking at entities that are in the deck at mulligan time.
